### ISSUE TITLE
Legal "Safety Check" Feature

### ISSUE THREAD

**Issue by glich509** [infamousjoeg/DNAmicAnalysis#21]
1. Ask the user to type the name of the customer AD domain they think they're analyzing
	2. The tool compares that value with the domain names that appear in the Account Type field
		a. If there is a match, proceed to analyze.  Print informational message saying there was a match.
		b. If there is NOT a match:
			i. Present both: the domain names from the report & what the user typed on the screen 
			ii. Ask the user to confirm that despite the discrepancy they want to continue (y/n)
			iii. If they say "no", terminate.  If they say "yes" proceed to analyze.

**Comment by glich509** [comment]
Addendum: If the domain name look up finds a match for the user supplied domain but there are also multiple other domain names besides that, print an informational message saying "user supplied domain matched 1 of X domains found in the report".  List all the domains found and ask the user if they'd like to continue.

**Comment by glich509** [comment]
Addendum II: Ignore domains that did not resolve properly and present in a SID format "e.g. S-1-5-21-1989350306-924044511-1912976903-11613"

**Comment by infamousjoeg** [comment]
# Feature Workflow

* User Input: What AD Domain?
* SQL Query: Grab domains scanned from Accounts table [data/sql/ADDomainCheck.sql](data/sql/ADDomainCheck.sql)
* Conditional Statement:
  * IF match: print domain found and proceed
    * IF match + multiple domains: print domain found out of total and proceed
  * ELSE: print the domain names found and the User Input
    * Ask the user to confirm they want to continue
      * IF: yes, proceed
      * ELSE: no, terminate

**Comment by infamousjoeg** [comment]
> Addendum: If the domain name look up finds a match for the user supplied domain but there are also multiple other domain names besides that, print an informational message saying "user supplied domain matched 1 of X domains found in the report". List all the domains found and ask the user if they'd like to continue.

List domains found if multiple on success, too.
