### ISSUE TITLE
Adjust database file name parsing logic

### ISSUE THREAD

**Issue by kazekan** [infamousjoeg/DNAmicAnalysis#76]
If someone decides to create a prefix for their DNA file using "CustomerAbbreviation_" so that the filename ends up being "Customer_DNA_DateTime.db", the current logic used to parse the filename will think that "DNA" is supposed to be the date, and the date is supposed to be the time. We may want to ignore anything before "DNA" instead of just going off the first "_" as the primary delimiter.

**Comment by infamousjoeg** [comment]
Can you confirm that this was not resolved in Pull Request #73 by switching to a config file that allows the ability to override the date & time stamp automation in cases where there's a malformed DNA database filename?

If it was not resolved, please elaborate on the preferred method of resolution.  Does it even make sense to read the filename anymore and just require the scan date & time to be set via config file?

**Comment by kazekan** [comment]
It's not so much that the date & time override _wouldn't_ resolve the issue (which it technically would, albeit with a lot more work on the user's part than is necessary IMO), it's that a simple prefix on the name of the database file along with another underscore completely kills DNAmic's ability to read the timestamp. Because you're just doing a `dbFileNameSplit = self._dbfile.split("_")` without any concern for what comes before the first "_" it can't handle a prefix that also includes a "_".

I think the best solution would be one in which the user could add such a prefix for their own organizational purposes (just in case they don't store them in folders or something) so as to not mix up database files and not get punished for it by having to override the date & time. What that actually looks like in the logic of the code I leave up to you, but we can brainstorm together if it'd be helpful.

**Comment by infamousjoeg** [comment]
Solution to test: `dnaIndex = dbFileNameSplit.index('DNA')` and then +1 to the returned index would be date... +1 more would be time.
