### ISSUE TITLE
Console output switch not working as likely intended

### ISSUE THREAD

**Issue by kazekan** [infamousjoeg/DNAmicAnalysis#78]
When setting console_output to "no", the tool simply produces no output whatsoever, even in Excel form. I believe the intention here was to skip the sometimes tedious step of hitting Enter a bunch of times within the console since all of the data is going to get pushed into an Excel file anyway. Otherwise, the current behavior of this setting when set to "no" defeats the purpose of running the tool in the first place.

**Comment by infamousjoeg** [comment]
When this was built, I was under the impression the Excel spreadsheet was a temporary measure.  Will make this change.
