### ISSUE TITLE
Change name for "Accounts with Multiple Machine Hashes" metric

### ISSUE THREAD

**Issue by kazekan** [infamousjoeg/DNAmicAnalysis#80]
This particular metric is measuring how many _other_ servers you could access _if a hash were found at all_, and is not reliant upon multiple hashes being found in order to make it onto this list. Therefore, the title is a bit misleading because in the event we find a single hash but that hash could be used to access 1000 servers, that account will definitely make it into this list. The title should be adjusted to, "Account hashes that expose multiple machines". This is something we should have for the GA version for sure.

**Comment by infamousjoeg** [comment]
Resolved in v0.5.0-beta.4 release
