### ISSUE TITLE
UnboundLocalError: local variable 'sqlQueryFinal' referenced before assignment

### ISSUE THREAD

**Issue by BinaryWasp** [infamousjoeg/DNAmicAnalysis#91]
PS C:\_CSTools\DNAmicAnalysis-0.3.0-beta.2> python .\DNAmicAnalysis.py '.\data\ClientRedacted\DNA_2019-10-07_11_59-59-PM.db' -d "cyberarkdemo.com" -s "svc" -a "adm" -t
Traceback (most recent call last):
  File ".\DNAmicAnalysis.py", line 476, in <module>
    main(args)
  File ".\DNAmicAnalysis.py", line 48, in main
    domain_names = db.exec_fromfile("data/sql/ADDomainCheck.sql")
  File "C:\_CSTools\DNAmicAnalysis-0.3.0-beta.2\dnamic_analysis\database.py", line 90, in exec_fromfile
    c.execute(sqlQueryFinal)
UnboundLocalError: local variable 'sqlQueryFinal' referenced before assignment
PS C:\_CSTools\DNAmicAnalysis-0.3.0-beta.2>

**Comment by infamousjoeg** [comment]
Tried finding client's database this was run on.  All databases were obfuscated.  Waiting on confirmation from field.

**Comment by infamousjoeg** [comment]
Closed until further notice.
